### PR TITLE
Added missing entry

### PR DESCRIPTION
**Pull request by urbalazs**
Hi @dvuckovic 
OTRSAppointmentCalendar version 5.0.2 have been released, the upcoming version is 5.0.3

### CODE REVIEW

**Comment by urbalazs** [comment]
Hi @dvuckovic 
Can you check this PR? The current version in the Changes file is wrong.

**Comment by urbalazs** [comment]
Hi @dvuckovic
Can you check this PR? The current version in the Changes file is wrong.

**Comment by urbalazs** [comment]
Hi @mgruner 
Can you check this PR? The current version in the Changes file is wrong.

**Comment by mgruner** [comment]
@dvuckovic, @s7designcreative can you please check this?

**Comment by dvuckovic** [comment]
This has been fixed as part of a bugfix in 6bc84c06. Thanks for spotting @urbalazs, sorry it took so long!

**Pull request closed without merging**
